### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by michaelritsema** [FittedCloud/costreporter#2]
python costreporter.py -p default -t 2018-03-01,2018-03-30

The numbers are all over the place. Some looks like they might be accurate but others look like they might be year to date or all time ranges.

Columns that are so inflated they might be closer to all time values:

Amazon Elastic Block Store                            	    
Amazon Elastic Compute Cloud - Compute                	    
Tax

**Comment by G7Nation** [comment]
This should be fixed as of fde25fe.

The issue was that, while I thought I was fetching per-region values and aggregating them, the Cost Explorer API returns global values, so the results would be (correct value) * (number of regions) hence the inflated numbers.  Let me know if you see any more problems.  Thanks.
